{% set name = "excelcsvparsehelper" %}
{% set version = "1.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e89e37129a004f5819abb593e28cb3ea7eb7e49a29e0e0ea68b9a323158432c9

build:
  number: 0
  skip: true  # [not win or py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pandas >=2.0
    - openpyxl >=3.1.5
    - psutil  # [win]
    - pywin32  # [win]

test:
  imports:
    - ExcelCSVParseHelper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ExcelCSVParseHelper/
  license: BSD-3-Clause license
  license_file: LICENSE
  summary: Lightweight helpers for Excel/CSV on Windows.

extra:
  recipe-maintainers:
    - Marcin-kowalczyk-polenergia
