{% set name = "excelcsvparsehelper" %}
{% set version = "1.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cf070d60fe5dc7e182a714ca9f01cff7aee3e05163f9a42560a2b560223dbb5

build:
  number: 1
  skip: true  # [not win or py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pandas >=2.0
    - openpyxl >=3.1.5
    - psutil  # [win]
    - pywin32  # [win]

test:
  imports:
    - ExcelCSVParseHelper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ExcelCSVParseHelper/
  license: MIT
  license_file: LICENSE
  summary: Lightweight helpers for Excel/CSV on Windows.

extra:
  recipe-maintainers:
    - Marcin-kowalczyk-polenergia
