{% set name = "excelcsvparsehelper" %}
{% set version = "1.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2028e3bd661cf085fde7d88bb95d67ab88f96893295d51cbbfbca008c6d9c027

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - pandas >=2.0
    - openpyxl >=3.1.5
    - lockfilesemaphore >=3.0.2
    - psutil  # [win]
    - pywin32  # [win]

test:
  imports:
    - ExcelCSVParseHelper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ExcelCSVParseHelper/
  license: MIT
  license_file: LICENSE
  summary: Lightweight helpers for Excel/CSV (cross-platform; some Excel automation helpers are Windows-only).

extra:
  recipe-maintainers:
    - Marcin-kowalczyk-polenergia
